PL_MVC/Controllers/AlumnoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class AlumnoController : Controller
    {
        //
        // GET: /Alumno/
        public ActionResult GetAll()
        {
            ML.Alumno alumno = new ML.Alumno();
            ML.Result result = new ML.Result();
            ServiceReferenceAlumno.ServiceAlumnoClient service = new ServiceReferenceAlumno.ServiceAlumnoClient();
            var SL_result = service.GetAll(alumno);
            if (SL_result.Correct)
            {

            }
            var x = SL_result.Objects;
            result.Objects = SL_result.Objects.ToList();
            alumno.Alumnos = result.Objects;
            return View(alumno);
        }

        [HttpGet]
        public ActionResult Delete(int IdAlumno)
        {
            ML.Alumno alumno = new ML.Alumno();
            alumno.IdAlumno = IdAlumno;
            ServiceReferenceAlumno.ServiceAlumnoClient service = new ServiceReferenceAlumno.ServiceAlumnoClient();
            service.Delete(alumno);
            return RedirectToAction("GetAll");
        }

        [HttpGet]
        public ActionResult Form(int? IdAlumno)
        {
            ML.Alumno alumno = new ML.Alumno();
            alumno.IdAlumno = IdAlumno.GetValueOrDefault();

            if (IdAlumno == null)
            {
                return View(alumno);
            }
            else
            {
                ML.Result result = BL.Alumno.AlumnoGetById(alumno);

                if (result.Correct)
                {
                    alumno.IdAlumno = ((ML.Alumno)result.Object).IdAlumno;
                    alumno.Nombre = ((ML.Alumno)result.Object).Nombre;
                    alumno.ApellidoPaterno = ((ML.Alumno)result.Object).ApellidoPaterno;
                    alumno.ApellidoMaterno = ((ML.Alumno)result.Object).ApellidoMaterno;
                    return View(alumno);
                }
                else
                {
                    ViewBag.Message = result.ErrorMessage;
                    return PartialView("Modal");
                }
            }
        }

        [HttpPost] 
        public ActionResult Form(ML.Alumno alumno)
        {
            ML.Result result = new ML.Result();

            if (alumno.IdAlumno == 0)
            {
                ServiceReferenceAlumno.ServiceAlumnoClient service = new ServiceReferenceAlumno.ServiceAlumnoClient();
                var result_SL = service.Add(alumno);
                result.Correct = result_SL.Correct;
                result.ErrorMessage = result_SL.ErrorMessage;
                ViewBag.Message = "El alumno se agregó correctamente ";
                //return PartialView("Modal");
            }
            else
            {
                ServiceReferenceAlumno.ServiceAlumnoClient service = new ServiceReferenceAlumno.ServiceAlumnoClient();
                service.Update(alumno);
                var result_SL = service.Update(alumno);
                result.Correct = result_SL.Correct;
                result.ErrorMessage = result_SL.ErrorMessage;                
                ViewBag.Message = "El alumno se actualizó correctamente ";
                //return PartialView("Modal");
            }

            if (!result.Correct)
            {
                ViewBag.Message = "No se pudo agregar correctamente al alumno " + result.ErrorMessage;
            }
            return PartialView("Modal");
        }
	}
}

PL_MVC/Views/Alumno/Form.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h5>Alumno</h5>
        </div>
    </div>

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Alumno", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.IdAlumno, new { @class = "hidden" })
                            @Html.TextBoxFor(model => model.IdAlumno, new { @class = "form-control hidden" })
                            @Html.ValidationMessageFor(model => model.IdAlumno)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Nombre)
                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Nombre)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.ApellidoPaterno)
                            @Html.TextBoxFor(model => model.ApellidoPaterno, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ApellidoPaterno)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.ApellidoMaterno)
                            @Html.TextBoxFor(model => model.ApellidoMaterno, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.ApellidoMaterno)
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Alumno", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

PL_MVC/Views/Alumno/GetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/bootstrap.css" rel="stylesheet" />

<h2>Alumno</h2>

<div class="container">
    <div class="row">
        <div style="float:right; margin-bottom:1rem;">
            @Html.ActionLink("+", "Form", "Alumno", htmlAttributes: new { @class = "btn btn-success" })
        </div>

        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <td class="text-center">Editar</td>
                    <td class="hidden">IdAlumno</td>
                    <td class="text-center">Nombre</td>
                    <td class="text-center">ApellidoPaterno</td>
                    <td class="text-center">ApellidoMaterno</td>
                    <td class="text-center">Eliminar</td>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Alumno alumno in Model.Alumnos)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Alumno", new { IdAlumno = alumno.IdAlumno })"></a></td>
                        <td class="hidden">@alumno.IdAlumno</td>
                        <td class="text-center">@alumno.Nombre</td>
                        <td class="text-center">@alumno.ApellidoPaterno</td>
                        <td class="text-center">@alumno.ApellidoMaterno</td>
                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Alumno", new { IdAlumno = alumno.IdAlumno })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PL_MVC/Views/Alumno/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-md-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>