PL_MVC/Controllers/AlumnoMateriaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PL_MVC.Controllers
{
    public class AlumnoMateriaController : Controller
    {
        //
        // GET: /AlumnoMateria/
        public ActionResult AlumnoGetAll()
        {
            ML.Result result = BL.Alumno.AlumnoGetAll();
            ML.Alumno alumno = new ML.Alumno();
            alumno.Alumnos = result.Objects;
            return View(alumno);
        }

        public ActionResult AlumnoMateriaGetAsignadasByIdAlumno(int IdAlumno)
        {
            ML.Result result = new ML.Result();
            ML.AlumnoMateria alumnoMateria = new ML.AlumnoMateria();
            alumnoMateria.Alumno = new ML.Alumno();
            alumnoMateria.Alumno.IdAlumno = IdAlumno;
            result = BL.Alumno.AlumnoGetById(alumnoMateria.Alumno);
            if (result.Object != null)
            {
                ML.Alumno alumnoItem = new ML.Alumno();
                alumnoItem.IdAlumno = ((ML.Alumno)result.Object).IdAlumno;
                alumnoItem.Nombre = ((ML.Alumno)result.Object).Nombre;
                alumnoItem.ApellidoPaterno = ((ML.Alumno)result.Object).ApellidoPaterno;
                alumnoItem.ApellidoMaterno = ((ML.Alumno)result.Object).ApellidoMaterno;
            }
            //alumnoMateria.Materia = new ML.Materia();
            alumnoMateria.Alumno = (ML.Alumno)result.Object;
            result = BL.AlumnoMateria.AlumnoMateriaGetAsignadasByIdAlumno(alumnoMateria);
            alumnoMateria.AlumnoMaterias = result.Objects;
            return View(alumnoMateria);
        }

        public ActionResult AlumnoMateriaGetNotAsignadasByIdAlumno(int IdAlumno)
        {
            ML.Result result = new ML.Result();
            ML.AlumnoMateria alumnoMateria = new ML.AlumnoMateria();
            alumnoMateria.Alumno = new ML.Alumno();
            alumnoMateria.Alumno.IdAlumno = IdAlumno;
            result = BL.Alumno.AlumnoGetById(alumnoMateria.Alumno);
            if (result.Object != null)
            {
                ML.Alumno alumnoItem = new ML.Alumno();
                alumnoItem.IdAlumno = ((ML.Alumno)result.Object).IdAlumno;
                alumnoItem.Nombre = ((ML.Alumno)result.Object).Nombre;
                alumnoItem.ApellidoPaterno = ((ML.Alumno)result.Object).ApellidoPaterno;
                alumnoItem.ApellidoMaterno = ((ML.Alumno)result.Object).ApellidoMaterno;
            }
            alumnoMateria.Alumno = (ML.Alumno)result.Object;
            //alumnoMateria.Materia = new ML.Materia();
            result = BL.AlumnoMateria.AlumnoMateriaGetNotAsignadasByIdAlumno(alumnoMateria);
            alumnoMateria.AlumnoMaterias = result.Objects;
            return View(alumnoMateria);

            //ML.AlumnoMateria alumnoMateria = new ML.AlumnoMateria();
            //alumnoMateria.Alumno = new ML.Alumno();
            //alumnoMateria.Alumno.IdAlumno = IdAlumno;
            //alumnoMateria.Materia = new ML.Materia();
            //ML.Result result = BL.AlumnoMateria.AlumnoMateriaGetNotAsignadasByIdAlumno(alumnoMateria);
            //alumnoMateria.AlumnoMaterias = result.Objects;
            //return View(alumnoMateria);
        }

        [HttpPost]
        public ActionResult AlumnoMateriaGetNotAsignadasByIdAlumno(ML.AlumnoMateria alumnoMateria, int IdAlumno)
        {
            if (alumnoMateria.AlumnoMaterias != null)
            {
                foreach (string IdMateria in alumnoMateria.AlumnoMaterias)
                {
                    ML.AlumnoMateria alumnoMateriaItem = new ML.AlumnoMateria();

                    alumnoMateriaItem.Alumno = new ML.Alumno();
                    alumnoMateriaItem.Alumno.IdAlumno = IdAlumno;

                    alumnoMateriaItem.Materia = new ML.Materia();
                    alumnoMateriaItem.Materia.IdMateria = int.Parse(IdMateria);
                    ML.Result result = BL.AlumnoMateria.Add(alumnoMateriaItem);
                }
            }
            return RedirectToAction("AlumnoMateriaGetAsignadasByIdAlumno", new { IdAlumno });
        }

        public ActionResult Delete(int IdAlumnoMateria, int IdAlumno)
        {
            ML.AlumnoMateria alumnoMateria = new ML.AlumnoMateria();
            alumnoMateria.Alumno = new ML.Alumno();
            alumnoMateria.Alumno.IdAlumno = IdAlumno;
            alumnoMateria.IdAlumnoMateria = IdAlumnoMateria;
            ML.Result result = BL.AlumnoMateria.AlumnoMateriaDelete(alumnoMateria);
            if (result.Correct)
            {
                return RedirectToAction("AlumnoMateriaGetAsignadasByIdAlumno", new { IdAlumno });
            }
            else
            {
                result.ErrorMessage = "Hubo un problema";
            }
            return RedirectToAction("AlumnoMateriaGetAsignadasByIdAlumno?", new { IdAlumno });        
        }
	}
}

PL_MVC/Views/AlumnoMateria/AlumnoGetAll.cshtml
@model ML.Alumno
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/bootstrap.css" rel="stylesheet" />

<h2>Lista de Alumno</h2>

<div class="container">
    <div class="row">
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <td class="text-center">Seleccionar</td>
                    <td class="hidden">IdAlumno</td>
                    <td class="text-center">Nombre</td>
                    <td class="text-center">ApellidoPaterno</td>
                    <td class="text-center">ApellidoMaterno</td>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Alumno alumno in Model.Alumnos)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-default glyphicon glyphicon-share-alt" href="@Url.Action("AlumnoMateriaGetAsignadasByIdAlumno", "AlumnoMateria", new { IdAlumno = alumno.IdAlumno })"></a></td>
                        <td class="hidden">@alumno.IdAlumno</td>
                        <td class="text-center">@alumno.Nombre</td>
                        <td class="text-center">@alumno.ApellidoPaterno</td>
                        <td class="text-center">@alumno.ApellidoMaterno</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PL_MVC/Views/AlumnoMateria/AlumnoMateriaGetAsignadasByIdAlumno.cshtml
@model ML.AlumnoMateria
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/bootstrap.css" rel="stylesheet" />

<h2>Materias Asignadas</h2>
<div class="row">
    <div class="col-md-6">
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-addon">Nombre</span>
            @Html.TextBoxFor(model => model.Alumno.Nombre, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-addon">Apellido Paterno</span>
            @Html.TextBoxFor(model => model.Alumno.ApellidoPaterno, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-addon">Apellido Materno</span>
            @Html.TextBoxFor(model => model.Alumno.ApellidoMaterno, new { @class = "form-control", @readonly = "readonly" })
        </div>
    </div>
</div>
<a class="btn btn-default" href="@Url.Action("AlumnoGetAll", "AlumnoMateria")"><span class="glyphicon glyphicon-chevron-left"></span></a>
<div class="container">
    <div class="row">
        <div style="float:right; margin-bottom:1rem;">
            <a class="btn btn-success " href="@Url.Action("AlumnoMateriaGetNotAsignadasByIdAlumno", "AlumnoMateria", new { IdAlumno = Model.Alumno.IdAlumno })"><span>+</span></a>
        </div>

        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <td class="text-center">Eliminar</td>
                    <td class="hidden">IdAlumnoMateria</td>
                    <td class="hidden">IdAlumno</td>
                    <td class="text-center">Nombre</td>
                    <td class="text-center">Costo</td>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.AlumnoMateria alumnoMateria in Model.AlumnoMaterias)
                    {
                        <tr>
                            <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "AlumnoMateria", new { IdAlumnoMateria = alumnoMateria.IdAlumnoMateria, IdAlumno = alumnoMateria.Alumno.IdAlumno })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                            <td class="hidden">@alumnoMateria.IdAlumnoMateria</td>
                            <td class="hidden">@alumnoMateria.Alumno.IdAlumno</td>
                            <td class="text-center">@alumnoMateria.Materia.Nombre</td>
                            <td class="text-center">@alumnoMateria.Materia.Costo</td>
                        </tr>
                    }           
            </tbody>
        </table>
    </div>
</div>

PL_MVC/Views/AlumnoMateria/AlumnoMateriaGetNotAsignadasByIdAlumno.cshtml
@model ML.AlumnoMateria
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/bootstrap.css" rel="stylesheet" />

<h2>Materias Disponibles:</h2>
<div class="row">
    <div class="col-md-6">
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-addon">Nombre</span>
            @Html.TextBoxFor(model => model.Alumno.Nombre, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-addon">Apellido Paterno</span>
            @Html.TextBoxFor(model => model.Alumno.ApellidoPaterno, new { @class = "form-control", @readonly = "readonly" })
        </div>
        <div class="input-group input-group-sm mb-3">
            <span class="input-group-addon">Apellido Materno</span>
            @Html.TextBoxFor(model => model.Alumno.ApellidoMaterno, new { @class = "form-control", @readonly = "readonly" })
        </div>
    </div>
</div>
<a class="btn btn-default" href="@Url.Action("AlumnoMateriaGetAsignadasByIdAlumno", "AlumnoMateria", new { Model.Alumno.IdAlumno })"><span class="glyphicon glyphicon-chevron-left"></span></a>
<div class="container">
    <div class="row">
        @using (Html.BeginForm("AlumnoMateriaGetNotAsignadasByIdAlumno", "AlumnoMateria", FormMethod.Post, new { enctype = "multipart/form-data" }))
        {
            <input type="hidden" value="@Model.Alumno.IdAlumno" name="IdAlumno" />
        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <td class="text-center">Seleccionar</td>
                    <td class="hidden">IdAlumnoMateria</td>
                    <td class="text-center">Nombre</td>
                </tr>
            </thead>               
            <tbody>               
                    @foreach (ML.AlumnoMateria alumnoMateria in Model.AlumnoMaterias)
                {
                    <tr>
                        <td class="text-center"><input type="checkbox" value="@alumnoMateria.Materia.IdMateria" name="AlumnoMaterias"></td>
                        <td class="hidden">@alumnoMateria.IdAlumnoMateria</td>
                        <td class="text-center">@alumnoMateria.Materia.Nombre</td>
                    </tr>
                }                              
            </tbody>
        </table>
            <div class="text-center">
            <input class="btn btn-success" type="submit" value="Guardar" />
            </div>
        }       
    </div>
</div>