PL_MVC/Controllers/MateriaController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Http;

namespace PL_MVC.Controllers
{
    public class MateriaController : Controller
    {
        //
        // GET: /Materia/
        public ActionResult GetAll()
        {
            ML.Result resultMateriaAPI = new ML.Result();
            resultMateriaAPI.Objects = new List<Object>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri("http://localhost:1040/");

                var responseTask = client.GetAsync("api/materia");
                responseTask.Wait();

                var result = responseTask.Result;

                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<ML.Result>();
                    readTask.Wait();

                    foreach (var resultItem in readTask.Result.Objects)
                    {
                        ML.Materia resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Materia>(resultItem.ToString());
                        resultMateriaAPI.Objects.Add(resultItemList);
                    }
                }
            }

            ML.Materia materia = new ML.Materia();
            materia.Materias = resultMateriaAPI.Objects;
            return View(materia);
        }

        [HttpGet]
        public ActionResult Delete(int IdMateria)
        {
            ML.Result resultMateriaList = new ML.Result();
            using (var materia = new HttpClient())
            {
                materia.BaseAddress = new Uri("http://localhost:1040/");
                var postTask = materia.DeleteAsync("api/materia/" + IdMateria);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    return RedirectToAction("GetAll");
                }
            }
            return RedirectToAction("GetAll");
        }

        [HttpGet]
        public ActionResult Form(int? IdMateria) 
        {
            ML.Materia materia = new ML.Materia();
            materia.IdMateria = IdMateria.GetValueOrDefault();

            if (IdMateria == null)//Add
            {
                return View(materia);
            }
            else
            {
                ML.Result result = GetByIdAPI(IdMateria);

                if (result.Correct)
                {
                    materia.IdMateria = ((ML.Materia)result.Object).IdMateria;
                    materia.Nombre = ((ML.Materia)result.Object).Nombre;
                    materia.Costo = ((ML.Materia)result.Object).Costo;
                    return View(materia);
                }
                else
                {
                    ViewBag.Message = result.ErrorMessage;
                    return PartialView("Modal");
                }
            }
        }

        [HttpPost]
        public ActionResult Form(ML.Materia materia)
        {
            var id = materia.IdMateria;
            ML.Result result = new ML.Result();

            if (materia.IdMateria == 0)//Add
            {
                using (var materiaItem = new HttpClient())
                {
                    materiaItem.BaseAddress = new Uri("http://localhost:1040/");

                    var postTask = materiaItem.PostAsJsonAsync<ML.Materia>("api/materia/", materia);
                    postTask.Wait();

                    var resultPost = postTask.Result;
                    if (resultPost.IsSuccessStatusCode)
                    {
                        ViewBag.Message = "La materia se agregó correctamente ";
                        return PartialView("Modal");
                    }
                }

            }
            else
            {
                using (var materiaItem = new HttpClient())
                {
                    materiaItem.BaseAddress = new Uri("http://localhost:1040/");

                    var postTask = materiaItem.PutAsJsonAsync<ML.Materia>("api/materia/" + id, materia);
                    postTask.Wait();

                    var resultPost = postTask.Result;
                    if (resultPost.IsSuccessStatusCode)
                    {
                        ViewBag.Message = "La materia se actualizó correctamente ";
                        return PartialView("Modal");
                    }
                }

            }

            //if (!result.Correct)
            //{
            //    ViewBag.Message = "No se pudo agregar correctamente el departamento " + result.ErrorMessage;
            //}

            return PartialView("Modal");
        }


        public static ML.Result GetByIdAPI(int? IdMateria)
        {
            ML.Result result = new ML.Result();
            try
            {
                string urlAPI = System.Configuration.ConfigurationManager.AppSettings["http://localhost:1040/"];
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri("http://localhost:1040/");
                    var responseTask = client.GetAsync("api/materia/" + IdMateria);
                    responseTask.Wait();
                    var resultAPI = responseTask.Result;

                    if (resultAPI.IsSuccessStatusCode)
                    {
                        var readTask = resultAPI.Content.ReadAsAsync<ML.Result>();
                        readTask.Wait();
                        ML.Materia resultItemList = new ML.Materia();
                        resultItemList = Newtonsoft.Json.JsonConvert.DeserializeObject<ML.Materia>(readTask.Result.Object.ToString());
                        result.Object = resultItemList;
                        result.Correct = true;
                    }
                    else
                    {
                        result.Correct = false;
                        result.ErrorMessage = "No existen registros en la tabla Materia";
                    }
                }
            }
            catch (Exception Ex)
            {
                result.Correct = false;
                result.ErrorMessage = Ex.Message;
            }
            return result;
        }
	}
}

PL_MVC/Views/Materia/Form.cshtml
@model ML.Materia
@{
    ViewBag.Title = "Form";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h5>Materia</h5>
        </div>
    </div>

    <script src="~/Scripts/jquery-3.4.1.js"></script>
    <script src="~/Scripts/bootstrap.js"></script>
    <link href="~/Content/bootstrap.css" rel="stylesheet" />

    <div class="row">
        <div class="col-md-12">
            @using (Html.BeginForm("Form", "Materia", FormMethod.Post, new { enctype = "multipart/form-data" }))
            {
                <div class="form-horizontal">
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.IdMateria, new { @class = "hidden" })
                            @Html.TextBoxFor(model => model.IdMateria, new { @class = "form-control hidden" })
                            @Html.ValidationMessageFor(model => model.IdMateria)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Nombre)
                            @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Nombre)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-3">
                            @Html.LabelFor(model => model.Costo)
                            @Html.TextBoxFor(model => model.Costo, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.Costo)
                        </div>
                    </div>
                    <br />
                    <div class="form-group">
                        <div class="col-md-3">
                            <input type="submit" value="Guardar" class="btn btn-success" />
                            @Html.ActionLink("Regresar", "GetAll", "Materia", htmlAttributes: new { @class = "btn btn-danger" })
                        </div>
                    </div>
                </div>
            }
        </div>
    </div>
</div>

PL_MVC/Views/Materia/GetAll.cshtml
@model ML.Materia
@{
    ViewBag.Title = "GetAll";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<link href="~/Content/bootstrap.css" rel="stylesheet" />

<h2>Materia</h2>

<div class="container">
    <div class="row">
        <div style="float:right; margin-bottom:1rem;">
            @Html.ActionLink("+", "Form", "Materia", htmlAttributes: new { @class = "btn btn-success" })
        </div>

        <table class="table table-bordered table-responsive">
            <thead>
                <tr>
                    <td class="text-center">Editar</td>
                    <td class="hidden">IdMateria</td>
                    <td class="text-center">Nombre</td>
                    <td class="text-center">Costo</td>
                    <td class="text-center">Eliminar</td>
                </tr>
            </thead>
            <tbody>
                @foreach (ML.Materia materia in Model.Materias)
                {
                    <tr>
                        <td class="text-center"><a class="btn btn-warning glyphicon glyphicon-edit" href="@Url.Action("Form", "Materia", new { IdMateria = materia.IdMateria })"></a></td>
                        <td class="hidden">@materia.IdMateria</td>
                        <td class="text-center">@materia.Nombre</td>
                        <td class="text-center">@materia.Costo</td>
                        <td class="text-center"><a class="btn btn-danger glyphicon glyphicon-trash" href="@Url.Action("Delete", "Materia", new { IdMateria = materia.IdMateria })" onclick="return confirm('Estas seguro que deseas eliminar este registro?');"></a></td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

PL_MVC/Views/Materia/Modal.cshtml
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
<script src="http://bootboxjs.com/bootbox.js"></script>
<link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">

<div class="modal" tabindex="-1" role="dialog" id="modalValidacion">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">Aviso</h4>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <h5>@ViewBag.Message</h5>
            </div>
            <div class="modal-footer">
                @Html.ActionLink("Regresar", "GetAll", "Departamento", htmlAttributes: new { @class = "btn btn-md-danger" })
            </div>
        </div>
    </div>
</div>

<script>
    $('#modalValidacion').modal();
</script>